version: '3.9'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - rancher_data:/var/lib/rancher

volumes:
  rancher_data:
